Lamb_Ji_Gestion/Lamb_Ji_UI/Controllers/ClubController.cs
using Lamb_Ji_DAL;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lamb_Ji_UI.Controllers
{
    public class ClubController : Controller
    {
        CNGLUTTEDBEntities db = new CNGLUTTEDBEntities();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddNewClub()
        {
            return View();
        }

        public ActionResult SaveData(Club item)
        {
            if (item.ClubName !=null && item.ClubAdresse != null && item.ClubEmail != null && item.ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(item.ImageUpload.FileName);
                string extension = Path.GetExtension(item.ImageUpload.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssff")+ extension;
                item.imageUrl = fileName;
                item.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Image-Club"), fileName));
                db.Clubs.Add(item);
                db.SaveChanges();
            }
            var result = "Ajouté avec succés!!!";
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

Lamb_Ji_Gestion/Lamb_Ji_UI/Controllers/LutteurController.cs
using Lamb_Ji_DAL;
using Lamb_Ji_ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lamb_Ji_UI.Controllers
{
    public class LutteurController : Controller
    {
        CNGLUTTEDBEntities db = new CNGLUTTEDBEntities();

        public ActionResult Index()
        {
            List<Club> LutList = db.Clubs.ToList();
            ViewBag.ListOfLutteur = new SelectList(LutList, "ClubID", "ClubName");

            return View();
        }

        public ActionResult ViewAll()
        {
            List<Club> LutList = db.Clubs.ToList();
            ViewBag.ListOfLutteur = new SelectList(LutList, "ClubID", "ClubName");

            List<Lutteur> LutteursDb = db.Lutteurs.ToList();
            List<LutteurViewModel> LutteursVM = new List<LutteurViewModel>();
            foreach (var item in LutteursDb)
            {
                LutteurViewModel Lvm = AutoMapper.Mapper.Map<LutteurViewModel>(item);

                Lvm.Club = db.Clubs.Where(a => a.ClubID == item.LutteurClubID).FirstOrDefault();

                LutteursVM.Add(Lvm);
            }

            return View(LutteursVM);
        }
        public JsonResult GetLutteurList()
        {
            List<Lutteur> LutteursDb = db.Lutteurs.ToList();
            List<LutteurViewModel> LutteursVM = new List<LutteurViewModel>();
            foreach (var item in LutteursDb)
            {
                LutteurViewModel Lvm = new LutteurViewModel();
                Lvm.LutteurID = item.LutteurID;
                Lvm.LutteurClubID = item.LutteurClubID;
                Lvm.LutteurName = item.LutteurName;
                Lvm.LutteurEmail = item.LutteurEmail;
                Lvm.LutteurDescription = item.LutteurDescription;
                Lvm.LutteurAddresse = item.LutteurAddresse;
                Lvm.LutteurDateNaissance = item.LutteurDateNaissance;
                Lvm.LutteurPoids = item.LutteurPoids;
                Lvm.LutteurTelephone = item.LutteurTelephone;
                Lvm.ClubName = item.Club.ClubName;

                LutteursVM.Add(Lvm);
            }

            return Json(LutteursVM, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetLutteurById(int LutteurID)
        {
            Lutteur model = db.Lutteurs.Where(x => x.LutteurID == LutteurID).Include(c => c.Club).FirstOrDefault();
            string value = string.Empty;
            value = JsonConvert.SerializeObject(model, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Json(value, JsonRequestBehavior.AllowGet);
        }

        //[ValidateAntiForgeryToken]
        public JsonResult SaveDataInDatabase(LutteurViewModel model)
        {
            var result = false;
            if (ModelState.IsValid) { 
                try
            {
          
                    if (model.LutteurID > 0)
                {
                    Lutteur Lut = db.Lutteurs.Include(c => c.Club).SingleOrDefault(x => x.LutteurID == model.LutteurID);
                    Lut.LutteurName = model.LutteurName;
                    Lut.LutteurEmail = model.LutteurEmail;
                    Lut.LutteurDateNaissance = model.LutteurDateNaissance;
                    Lut.LutteurDescription = model.LutteurDescription;
                    Lut.LutteurPoids = model.LutteurPoids;
                    Lut.LutteurTelephone = model.LutteurTelephone;
                    Lut.LutteurAddresse = model.LutteurAddresse;
                    Lut.imageUrl = model.imageUrl;
                    Lut.LutteurClubID = model.LutteurClubID;
                    db.SaveChanges();
                    result = true;
                }
                else
                {
                        if (model.ImageUpload != null)
                        {
                            string fileName = Path.GetFileNameWithoutExtension(model.ImageUpload.FileName);
                            string extension = Path.GetExtension(model.ImageUpload.FileName);
                            fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
                            model.imageUrl = fileName;
                            model.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Image-Lutteur"), fileName));
                        }

                        Lutteur Lut = new Lutteur();
                    Lut.LutteurName = model.LutteurName;
                    Lut.LutteurEmail = model.LutteurEmail;
                    Lut.LutteurDateNaissance = model.LutteurDateNaissance;
                    Lut.LutteurDescription = model.LutteurDescription;
                    Lut.LutteurPoids = model.LutteurPoids;
                    Lut.LutteurTelephone = model.LutteurTelephone;
                    Lut.LutteurAddresse = model.LutteurAddresse;
                    Lut.imageUrl = model.imageUrl;
                    Lut.LutteurClubID = model.LutteurClubID;
                    db.Lutteurs.Add(Lut);
                    db.SaveChanges();
                    result = true;
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
            }
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public JsonResult DeleteLutteurRecord(int LutteurID)
        {
            bool result = false;
            Licence lic = db.Licences.SingleOrDefault(a => a.LutteurID == LutteurID);
            Lutteur Lut = db.Lutteurs.SingleOrDefault(x => x.LutteurID == LutteurID);
            if (lic == null)
            {
                if (Lut != null)
                {
                    db.Lutteurs.Remove(Lut);
                    db.SaveChanges();
                    result = true;
                }
            }
            else
            {
                db.Licences.Remove(lic);
                db.Lutteurs.Remove(Lut);
                db.SaveChanges();
                result = true;

            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }


      
    }
}

Lamb_Ji_Gestion/Lamb_Ji_UI/Controllers/MenuAccueilController.cs
using Lamb_Ji_DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Lamb_Ji_UI.Controllers
{
    public class MenuAccueilController : Controller
    {
        // GET: MenuAccueil
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Menu()
        {

            List<MenuDynamique> list = new List<MenuDynamique>();
            list.Add(new MenuDynamique { Lien = "#", NomLien = "ACCUEIL" });
            list.Add(new MenuDynamique { Lien = "#", NomLien = "LUTTEURS" });
            list.Add(new MenuDynamique { Lien = "#", NomLien = "COMBATS A VENIR" });
            list.Add(new MenuDynamique { Lien = "#", NomLien = "ACTUALITES" });
            list.Add(new MenuDynamique { Lien = "#",/*/Club/AddNewClub*/ NomLien = "STADES" });



            return PartialView("MenuDynam", list);
        }
    }
}

Lamb_Ji_Gestion/Lamb_Ji_UI/Views/Shared/MenuDynam.cshtml
@model IEnumerable<Lamb_Ji_DAL.MenuDynamique>

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Menu</h2>
    </div>
    <div class="panel-body">
        <ul class="list-group">

            @if (Model != null)
            {

                foreach (var item in Model)
                {

                    <li class="list-group-item"><a href="@item.Lien" class="btn btn-primary btn-block">@item.NomLien</a></li>

                }
            }

            <li class="list-group-item"><a href="http://google.com" class="btn btn-success btn-block" target="_blank">Google</a></li>
            <li class="list-group-item"><a href="http://ephec.be" class="btn btn-warning btn-block" target="_blank">Mon Ecole</a></li>

        </ul>
    </div>
</div>

<div class="thumbnail">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">INFOS</h3>
        </div>
    </div>
    <img src="~/Pictures/3363065-4830807.jpg" />
    <div class="caption">
        <h3>Docteur Alioune Sarr</h3>
        <p>&para; Projet de gestion de la lutte senegalaise pour le cour de projet d'intégration blablabla blablabla. &para;</p>
        <p><a href="#" class="btn btn-primary" role="button">Voir plus...</a> </p>
    </div>
</div>

Lamb_Ji_Gestion/Lamb_Ji_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LAMB_JI GESTION</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/DataTables")

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            toastr.options = {
                "debug": false,
                "positionClass": "toast-bottom-right",
                "onclick": null,
                "fadeIn": 300,
                "fadeOut": 1000,
                "timeOut": 3000,
                "extendedTimeOut": 1000,
                "progressBar": true
            }
        });

    </script>

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

</head>
<body>

    <div class="panel panel-body" style="min-height:256px">
        <div class="col-md-3">

            @{ Html.RenderAction("Menu", "MenuAccueil");}

        </div>
        <div class="col-md-9">

            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("LAMB_JI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Clubs", "Index", "Club")</li>
                            <li>@Html.ActionLink("Slider", "AddImage", "Slider")</li>
                            <li>@Html.ActionLink("Stades", "Index", "Stade")</li>
                            <li>@Html.ActionLink("Gerer_Lutteurs", "Index", "Lutteur")</li>
                            <li>@Html.ActionLink("Arbitres", "Index", "Arbitre")</li>
                            <li>@Html.ActionLink("Affiche", "Index", "Affiche")</li>


                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
            @{ Html.RenderAction("SliderAccueil", "Slider");}

            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>PSR09133 Ndiack Fall - Lamb_Ji Gestion</p>
                </footer>
            </div>
        </div>
    </div>
   
</body>
</html>